name: junaedahmed.github.io
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
rouge: true
permalink: /blog/:year/:month/:title/
category_title_prefix: "Blog posts tagged with: "
category_dir: /blog/tags/
url: https://junaedahmed.github.io
